name: curl

on:
  workflow_dispatch:

jobs:
  curl-test:
    runs-on: arc-runner-set
    steps:
      - name: curl
        shell: bash
        run: |
          sudo apt-get update && sudo apt-get install -y curl
          $(which curl) -kv https://artifacts.rackspace.net/artifactory/signup-maven-local/
