name: curl

on:
  workflow_dispatch:

jobs:
  curl-test:
    runs-on: arc-runner-set
    steps:
      - name: curl
        shell: bash
        run: $(which curl) -kv https://artifacts.rackspace.net/artifactory/signup-maven-local/
